apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
        - name: java-web-app
          image: elliegwon/java-web-application:1.0.0-27
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
